export const COMMON_PLATFORMS = [
  'PC',
  'PlayStation 5',
  'PlayStation 4',
  'PlayStation 3',
  'Xbox Series X|S',
  'Xbox One',
  'Xbox 360',
  'Nintendo Switch',
  'Nintendo Switch 2',
  'Nintendo 3DS',
  'Wii U',
  'Wii',
  'Android',
  'iOS',
  'Mac',
  'Linux',
]
